spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false&serverTimezone=America/Los_Angeles
    driver-class-name: com.mysql.cj.jdbc.Driver