spring:
  profiles:
    active: dev
  messages:
    basename: i18n.login, i18n.others
  mvc:
    date-format: MM-dd-yyyy

person:
  age: 27
  boss: false
  birth-day: 1991/1/1
  map: {k1: v1, k2: v2}
  list: [lisi, 张三]
  dog:
    name: dog
    age: 12
