server:
  port: 8081

person:
  name: dev
  age: 27
  boss: false
  birth-day: 1991/1/1
  map: {k1: v1, k2: v2}
  list: [lisi, 张三]
  dog:
    name: dog
    age: 12

logging.file: logs/app.log
logging:
  pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  level:
    com:
      lzhao: debug
  file:
    max-size: 20MB
    max-history: 7
