spring:
  profiles:
    active: dev
  messages:
    basename: i18n.login, i18n.others
  mvc:
    date-format: MM-dd-yyyy
  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:mysql://localhost:3306/jdbcLearn
    driver-class-name: com.mysql.cj.jdbc.Driver

person:
  age: 27
  boss: false
  birth-day: 1991/1/1
  map: {k1: v1, k2: v2}
  list: [lisi, 张三]
  dog:
    name: dog
    age: 12
