spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbgirl?useSSL=false&serverTimezone=America/Los_Angeles
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true